### ISSUE TITLE
Brainstorm!

### ISSUE THREAD

**Issue by czeskij** [sdbrrn-team/tection#1]
ok, tutaj piszemy co tylko nam przyjdzie do głowy jako ficzery - będzie z czego wybierać. potem na podstawie tego rozpisze się mniejsze issues i milestone. :)

**Comment by Lamb3rt** [comment]
Bronie
Skille
Perspektywa (jak w Hotline Miami?)

**Comment by czeskij** [comment]
- grafika: pixelart
- mapa gry - przybliżona mapa naszego miejsca pracy
- multiplayer
- brak botów

**Comment by yyarp** [comment]
* kuboty dają +5 do poruszania się

**Comment by pein323** [comment]
> Bronie (książki, klawiatury, monitory, laptopy, krzesła)

A jak to by mialo wygladać posługiwanie się taką bronią?

**Comment by yyarp** [comment]
> Bronie (książki, klawiatury, monitory, laptopy, krzesła)
> A jak to by mialo wygladać posługiwanie się taką bronią?

rzucanie/napierdalanie?

**Comment by czeskij** [comment]
w ramach zapotrzebowania dodawać kolejne issue i dodawać label 'brainstorm'
