### ISSUE TITLE
Grafika

### ISSUE THREAD

**Issue by czeskij** [sdbrrn-team/tection#2]
wszystko fajnie ALE potrzebujemy assetów:
- na pewno postać - coś genericowego, jak w grach z których czerpiemy; głowa, popylające nogi, jakiś gnat w łapach
- na pewno jakiś zarys _pokoi_, który nas na początek _zaspokoi_ (tak idę już się zabić).

dodatkowo, obczajcie to - wygląda na sztosik narzędzie:
http://store.steampowered.com/app/431730/

**Comment by pein323** [comment]
Na początek żeby cokolwiek ruszyło po prostu jeden kwadrat w którym się chodzi, a potem by się to rozwijało. Ogarniemy jakie jest ogółem tempo rozwoju.
