### ISSUE TITLE
Struktura map

### ISSUE THREAD

**Issue by czeskij** [sdbrrn-team/tection#3]
jak to robimy, ziomeczki? pomysł padł, swoją drogą zajebisty, na stworzenie edytora map. #hypehype
nie mam doświadczenia w tworzeniu gier i jakiegoś dobrego workflow, no i tyle co Was znam to też długo w tym nie siedzieliście, ale wydaje mi się, że edytor to nie jest pomysł na wersję najpierwsiejszą, czyli 0.0.1 (patrzajcie w milestones co tam naskrobałem z grubsza).
nawiązując do idei pixelart, widzę tworzenie lokacji w jakimś systemie predefiniowanych kafelków (tiles), znamy to z wielu tytułów. taki kafelek składałby się z:
- kwadratowego sprite'a, rozmiar np. 64 x 64 px,
- odpowiednio dla rodzaju tile'a (zakręt, przesmyk, plain floor etc.) umieszczonych colliderów.

tyle wiem, potrzebuję pomysłów apropos tego co napisałem na początku - czy mam rację czy nie, no i jakichś dalszych rozkmin & sugestii.

**Comment by pein323** [comment]
Plus za kafelkami +
Co do edytora map to owszem należało by przesunąć to dalej jak będzie czym edytować. Na początek sugerowałbym utworzenie kilku obiekcików jak np podłoga po której porusza sie postać, jakaś ściana zeby ogarnąć kolizje itp. Mocno podstawowe rzeczy. Jak bedziemy mieć kwadrat po którym postać się będzie ruszać i strzelać to wtedy można dorzucać nowe obiekty i robić edytor map
