### ISSUE TITLE
Stworzenie prefaba postaci

### ISSUE THREAD

**Issue by czeskij** [sdbrrn-team/tection#6]
jakikolwiek sprite, hitboxy, poruszanie się (WASD + myszunia) _you know the rules, and so do I_
opisać użyte rozwiązanie w nowym artykule wiki.

**Comment by Lamb3rt** [comment]
Kwadracik już chodzi, jeszcze muszę ogarnąć kwestię obracania się w kierunku kursorsa.

**Comment by Lamb3rt** [comment]
Kwadracik elegancko się obraca.

**Comment by czeskij** [comment]
będzie commit dziś? ogarnąłbym #8 chętnie

**Comment by Lamb3rt** [comment]
Siedzi już na branchu osobnym.
