### ISSUE TITLE
Implementacja dynamicznej kamery

### ISSUE THREAD

**Issue by czeskij** [sdbrrn-team/tection#9]
Kamera podążająca za graczem. W obecnej wersji nie brać pod uwagę pola widzenia, które później powinno być jednakowe niezależnie od rozdzielczości gry (równe szanse w multiplayer, czyli uniknięcie sytuacji "zabiłeś mnie bo masz większy monitor").

**Comment by czeskij** [comment]
done, bardzo prosto ale zrobione. podesłałem do testu na discordzie. komentujcie

**Comment by Cry2tor** [comment]
ładnie to wygląda jak na pierwszą wersję. Nie wiem tylko czy nie za szybko się porusza gracz o.O

**Comment by czeskij** [comment]
ok, Wiktoria zauważyła to samo 😄 (nieoficjalny, jeszcze, beta-tester 😸 ). skorygujemy i sprawdzimy ale już nie dziś, Terminator 2 do obejrzenia ❤️

**Comment by dudkiputki** [comment]
fajne ale czy przód postaci nie powinien byc tam gdzie kursor ?
w sesie jak trzymam w to idzie za kursorem a jak a,d to przemieszcza sie na boki

**Comment by Lamb3rt** [comment]
Trochę bym oddalił kamerę, za duży zoom jest wydaje mi się.

**Comment by czeskij** [comment]
@Lamb3rt same here, ja bym nawet mocno oddalił ale mapa jest mała i to dlatego tylko.
@dudkiputki rozumiem, trzeba to sprawdzić, też się nad tym zastanawiam

**Comment by dudkiputki** [comment]
jest tu kto  ?

**Comment by czeskij** [comment]
@dudkiputki po prostu pisz, i tak każdy dostanie maila z powiadomieniem 😄 a jak nie tu to na discordzie (jeśli przypomnisz sobie nazwę 😆 )

**Comment by dudkiputki** [comment]
zabrałem vaio :D
